[
  {
    "id": 1,
    "name": "Emily Carter",
    "picture": "https://example.com/photo1.jpg",
    "email": "emily.carter@example.com",
    "days_since_contact": 5,
    "status": "active",
    "tags": ["work", "teammate"],
    "bio": "Works in the same project team.",
    "goal": 7,
    "next_due_date": "2025-07-10"
  },
  {
    "id": 2,
    "name": "Michael Brown",
    "picture": "https://example.com/photo2.jpg",
    "email": "michael.brown@example.com",
    "days_since_contact": 20,
    "status": "overdue",
    "tags": ["gym", "buddy"],
    "bio": "Workout partner from the gym.",
    "goal": 10,
    "next_due_date": "2025-07-05"
  },
  {
    "id": 3,
    "name": "Sophia Wilson",
    "picture": "https://example.com/photo3.jpg",
    "email": "sophia.wilson@example.com",
    "days_since_contact": 2,
    "status": "active",
    "tags": ["family"],
    "bio": "Cousin who lives abroad.",
    "goal": 15,
    "next_due_date": "2025-07-25"
  },
  {
    "id": 4,
    "name": "Daniel Lee",
    "picture": "https://example.com/photo4.jpg",
    "email": "daniel.lee@example.com",
    "days_since_contact": 9,
    "status": "due",
    "tags": ["client"],
    "bio": "Important business client.",
    "goal": 10,
    "next_due_date": "2025-07-12"
  },
  {
    "id": 5,
    "name": "Olivia Martinez",
    "picture": "https://example.com/photo5.jpg",
    "email": "olivia.m@example.com",
    "days_since_contact": 14,
    "status": "overdue",
    "tags": ["school", "friend"],
    "bio": "Old school friend from high school.",
    "goal": 12,
    "next_due_date": "2025-07-08"
  },
  {
    "id": 6,
    "name": "James Anderson",
    "picture": "https://example.com/photo6.jpg",
    "email": "james.anderson@example.com",
    "days_since_contact": 1,
    "status": "active",
    "tags": ["neighbor"],
    "bio": "Lives next door.",
    "goal": 7,
    "next_due_date": "2025-07-22"
  },
  {
    "id": 7,
    "name": "Ava Thomas",
    "picture": "https://example.com/photo7.jpg",
    "email": "ava.thomas@example.com",
    "days_since_contact": 16,
    "status": "overdue",
    "tags": ["travel", "friend"],
    "bio": "Travel buddy from last trip.",
    "goal": 10,
    "next_due_date": "2025-07-06"
  },
  {
    "id": 8,
    "name": "William Harris",
    "picture": "https://example.com/photo8.jpg",
    "email": "william.harris@example.com",
    "days_since_contact": 7,
    "status": "due",
    "tags": ["mentor"],
    "bio": "Career mentor and advisor.",
    "goal": 7,
    "next_due_date": "2025-07-15"
  },
  {
    "id": 9,
    "name": "Isabella Clark",
    "picture": "https://example.com/photo9.jpg",
    "email": "isabella.clark@example.com",
    "days_since_contact": 3,
    "status": "active",
    "tags": ["friend"],
    "bio": "Met at a conference.",
    "goal": 10,
    "next_due_date": "2025-07-18"
  },
  {
    "id": 10,
    "name": "Ethan Walker",
    "picture": "https://example.com/photo10.jpg",
    "email": "ethan.walker@example.com",
    "days_since_contact": 11,
    "status": "due",
    "tags": ["colleague"],
    "bio": "Office colleague from marketing.",
    "goal": 14,
    "next_due_date": "2025-07-11"
  },
  {
    "id": 11,
    "name": "Mia Hall",
    "picture": "https://example.com/photo11.jpg",
    "email": "mia.hall@example.com",
    "days_since_contact": 18,
    "status": "overdue",
    "tags": ["friend", "close"],
    "bio": "Best friend since childhood.",
    "goal": 7,
    "next_due_date": "2025-07-04"
  },
  {
    "id": 12,
    "name": "Lucas Young",
    "picture": "https://example.com/photo12.jpg",
    "email": "lucas.young@example.com",
    "days_since_contact": 6,
    "status": "active",
    "tags": ["startup"],
    "bio": "Co-founder of a startup.",
    "goal": 10,
    "next_due_date": "2025-07-16"
  }
]